const DataTypes = require('sequelize');
const db = require("../config/database");

const Clients = db.define('AccClient', {
  cln_L1: { type: DataTypes.NUMBER , defaultValue: 1104},
  cln_L2: { type: DataTypes.NUMBER },
  cln_L3: { type: DataTypes.NUMBER , defaultValue: 1},
  cln_L4: { type: DataTypes.NUMBER },
  cln_pass: { type: DataTypes.NUMBER },
  cln_username: { type: DataTypes.STRING },
  cln_birthdate: { type: DataTypes.DATE },
  cln_nam: { type: DataTypes.STRING },
  cln_enm: { type: DataTypes.STRING },
  cln_prd: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_lmt: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_whol: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_prsn: { type: DataTypes.STRING },
  cln_sale: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_sctr: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_phon: { type: DataTypes.STRING , defaultValue: ""},
  cln_fax: { type: DataTypes.STRING , defaultValue: ""},
  cln_mobl: { type: DataTypes.NUMBER },
  cln_box: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_zip: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_city: { type: DataTypes.STRING , defaultValue: ""},
  cln_area: { type: DataTypes.STRING , defaultValue: ""},
  cln_hold: { type: DataTypes.NUMBER , defaultValue: 0},
  cln_email: { type: DataTypes.STRING },
  cln_addr1: { type: DataTypes.STRING, defaultValue: '' },
  cln_addr2: { type: DataTypes.STRING, defaultValue: '' },
  cln_note: { type: DataTypes.STRING, defaultValue: '' },
  cln_key: { type: DataTypes.NUMBER, primaryKey: true, defaultValue: 0 },
  cln_state: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_date: { type: DataTypes.STRING },
  cln_comperc: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_salprc: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_categ: { type: DataTypes.NUMBER, defaultValue: 1 },
  cln_Long: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_Lat: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_typ: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_RegName: { type: DataTypes.STRING, defaultValue: '' },
  cln_RegNum: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_TaxNum: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_TaxTyp: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_TaxLocation: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_cur: { type: DataTypes.NUMBER, defaultValue: 0 },
  acc_jounral: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_bankname: { type: DataTypes.STRING, defaultValue: '' },
  cln_bankiban: { type: DataTypes.STRING, defaultValue: '' },
  cln_bankaddress: { type: DataTypes.STRING, defaultValue: '' },
  cln_bankcity: { type: DataTypes.STRING, defaultValue: '' },
  cln_bankswiftcode: { type: DataTypes.STRING, defaultValue: '' },
  cln_iddat1: { type: DataTypes.STRING, defaultValue: "" },
  cln_iddat2: { type: DataTypes.STRING, defaultValue: "" },
  cln_id_kind: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_cntry: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_bankcuntry: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_n: { type: DataTypes.NUMBER, defaultValue: 0 },
  cln_group: { type: DataTypes.NUMBER, defaultValue: 0 },
  clni_img: { type: DataTypes.STRING, defaultValue: '' },
  BuildingNumber: { type: DataTypes.NUMBER, defaultValue: 0 },
  PlotIdentification: { type: DataTypes.NUMBER, defaultValue: 0 },
  StreetName: { type: DataTypes.NUMBER, defaultValue: 0 },
  CitySubdivisionName: { type: DataTypes.NUMBER, defaultValue: 0 },
},
  {
    tableName: 'AccClient',
    timestamps: false,
  }
);
module.exports = Clients;