const  DataTypes  = require('sequelize');
const db = require("../config/database");

  const Clients = db.define('AccClient', {
    cln_L1: { type: DataTypes.NUMBER },
    cln_L2: { type: DataTypes.NUMBER },
    cln_L3: { type: DataTypes.NUMBER },
    cln_L4: { type: DataTypes.STRING },
    cln_nam: { type: DataTypes.STRING },
    cln_enm: { type: DataTypes.STRING },
    cln_prd: { type: DataTypes.NUMBER },
    cln_lmt: { type: DataTypes.NUMBER },
    cln_whol: { type: DataTypes.NUMBER },
    cln_prsn: { type: DataTypes.STRING },
    cln_sale: { type: DataTypes.NUMBER },
    cln_sctr: { type: DataTypes.NUMBER },
    cln_phon: { type: DataTypes.STRING },
    cln_fax: { type: DataTypes.STRING },
    cln_mobl: { type: DataTypes.NUMBER },
    cln_box: { type: DataTypes.NUMBER },
    cln_zip: { type: DataTypes.NUMBER },
    cln_city: { type: DataTypes.STRING },
    cln_area: { type: DataTypes.STRING },
    cln_hold: { type: DataTypes.NUMBER },
    cln_email: { type: DataTypes.STRING },
    cln_addr1: { type: DataTypes.STRING },
    cln_addr2: { type: DataTypes.STRING },
    cln_note: { type: DataTypes.STRING },
    cln_key: { type: DataTypes.NUMBER , primaryKey: true },
    cln_state: { type: DataTypes.NUMBER },
    cln_date: { type: DataTypes.DATE },
    cln_comperc: { type: DataTypes.NUMBER },
    cln_salprc: { type: DataTypes.NUMBER },
    cln_categ: { type: DataTypes.NUMBER },
    cln_Long: { type: DataTypes.NUMBER },
    cln_Lat: { type: DataTypes.NUMBER },
    cln_typ: { type: DataTypes.NUMBER },
    cln_RegName: { type: DataTypes.STRING },
    cln_RegNum: { type: DataTypes.NUMBER },
    cln_TaxNum: { type: DataTypes.NUMBER },
    cln_TaxTyp: { type: DataTypes.NUMBER },
    cln_TaxLocation: { type: DataTypes.NUMBER },
    cln_cur: { type: DataTypes.NUMBER },
    acc_jounral: { type: DataTypes.NUMBER },
    cln_bankname: { type: DataTypes.STRING },
    cln_bankiban: { type: DataTypes.STRING },
    cln_bankaddress: { type: DataTypes.STRING },
    cln_bankcity: { type: DataTypes.STRING },
    cln_bankswiftcode: { type: DataTypes.STRING },
    cln_iddat1: { type: DataTypes.DATE },
    cln_iddat2: { type: DataTypes.DATE },
    cln_id_kind: { type: DataTypes.NUMBER },
    cln_cntry: { type: DataTypes.NUMBER },
    cln_bankcuntry: { type: DataTypes.NUMBER },
    cln_n: { type: DataTypes.NUMBER },
    cln_group: { type: DataTypes.NUMBER },
    clni_img: { type: DataTypes.STRING },
    BuildingNumber: { type: DataTypes.NUMBER },
    PlotIdentification: { type: DataTypes.NUMBER },
    StreetName: { type: DataTypes.NUMBER },
    CitySubdivisionName: { type: DataTypes.NUMBER },
  },
   {
    tableName: 'AccClient',
    timestamps: false,
  }
);
  module.exports = Clients;